apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
# Snippet from https://github.com/helm/helm/issues/2573
{{ (tpl (.Files.Glob "files/*").AsConfig . ) | indent 2 }}
